language: java
jdk: oraclejdk8
sudo: false #faster builds
install: "mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)
